add_newline = true


format = """
$shell\
$username\
$directory\
$git_branch\
$git_status\
$fill\
$java\
$python\ 
$lua\
$cmd_duration\
$time\ 
$line_break\
$character"""


# Settings which are important for me every time.
[fill]
symbol = " "


[shell]
disabled = false
style = 'fg:bright-white'
bash_indicator = '[╭╴](fg:240)'
powershell_indicator = '[╭╴](fg:240)'


[username]
disabled = false
show_always = true
style_user = 'fg:bright-purple'
style_root = 'fg:bright-red'
format = '[$user]($style)'


[directory]
use_os_path_sep = false
truncation_length = 3
style = "fg:bright-green"
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "fg:red"
read_only = " "
format = " at [$read_only]($read_only_style)[$path]($style)"


[git_branch]
truncation_length = 10
style = "fg:bright-cyan"
truncation_symbol = "…"
symbol = " "
format = " on [$symbol$branch]($style)"


[git_status]
style = "fg:cyan"

# Github
up_to_date = "﫟"
ahead = "${count} "
diverged = "${ahead_count} ${behind_count} "
behind = "${count} "

# Local PC
untracked = "${count} "
conflicted = "${count}⚠" 
modified = "${count} "
staged = "${count} "
renamed = "${count}襁 "
deleted = "${count} "
stashed = " "

format = '[\($all_status$ahead_behind\)]($style)'


[cmd_duration]
style = "fg:yellow"
format = " [$duration]($style)"


[time]
disabled = false
style = "fg:bright-white"
format = " [$time]($style)"


[character]
success_symbol = "[╰╴](fg:240)[❱](fg:bright-green)"
error_symbol = "[╰╴](fg:240)[❱](fg:bright-red)"


# Settings to add some more functionality.
[python]
style = "fg:blue"
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'


[java]
style = "fg:bright-red"
symbol = ""
format = " [${symbol} (${version})]($style)"


[lua]
style = "fg:blue"
symbol = "⏾ "
format = " [${symbol} (${version})]($style)"