add_newline = true

format = """
$username\
$shell\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$os\
$python\
$java\
$c\
$nodejs\
$lua\
$line_break\
$character\
"""


[username]
style_user = 'fg:bright-yellow'
style_root = 'fg:bright-red'
format = '[\[](fg:red)[$user]($style)[@](fg:bright-green)'
disabled = false
show_always = true


[shell]
bash_indicator = 'Bash'
powershell_indicator = 'Pwsh'
style = 'fg:bright-cyan'
disabled = false


[directory]
truncation_length = 2
truncation_symbol = '…/'
home_symbol = '~'
read_only = ''
style = 'fg:bright-blue'
read_only_style = 'fg:red'
format = '[$read_only]($read_only_style)[$path]($style)'
disabled = false
use_os_path_sep = false
truncate_to_repo = false


[git_branch]
truncation_length = 8
truncation_symbol = '…'
style = 'fg:bright-purple'
format = '[\($branch]($style)'
only_attached = false
disabled = false


[git_commit]
commit_hash_length = 7
style = 'fg:bright-purple'
format = '[\($hash]($style)'
only_detached = true
tag_disabled = true
disabled = false


[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
style = 'fg:purple'
format = '[\($state\)]($style)'
disabled = false


[git_status]
style = 'bold green'
conflicted = '⚠'
up_to_date = ''
untracked = ''
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '⊞'
modified = '*'
staged = '+$count'
renamed = '~'
deleted = ''
format = '[$all_status$ahead_behind\)](bright-purple)'


[python]
format = ' ➜ \(󰌠 $pyenv_prefix$version(|$virtualenv)\)'


[java]
format = ' ➜ \( $version\)(bright-red)'


[lua]
format = ' ➜ \(⏾ $version|)(blue)'


[c]
format = ' ➜ \( $version\)(bright-blue)'


[nodejs]
format = ' ➜ \( $version\)(bright-green)'


[os]
format = '[\]](red)'
disabled = false


[character]
success_symbol = ''
error_symbol = ''
vimcmd_symbol = ''
