add_newline = true

format = """
$username\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$python\
$java\
$c\
$nodejs\
$lua\
$line_break\
$character\
"""


[username]
format = '[Admin](bright-red) in '
disabled = false
show_always = false


[shell]
bash_indicator = 'Bash'
powershell_indicator = 'Pwsh'
format = '[$indicator](bright-yellow) '
disabled = false


[directory]
truncation_length = 2
truncation_symbol = ''
home_symbol = '~'
read_only = '󰉐 '
read_only_style = 'red'
format = 'at [$read_only]($read_only_style)[$path](bright-green) '
disabled = false
use_os_path_sep = false
truncate_to_repo = false


[git_branch]
truncation_length = 8
truncation_symbol = '…'
format = 'on [󰊢 $branch](bright-cyan)'
only_attached = false
disabled = false


[git_commit]
commit_hash_length = 7
format = 'on [󰊢 $hash](bright-cyan)'
only_detached = true
tag_disabled = true
disabled = false


[git_status]
conflicted = '⚠'
up_to_date = ''
untracked = ''
ahead = '⇡${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = '⊞'
modified = '*'
staged = '+$count'
renamed = '~'
deleted = ''
format = '[(\($all_status$ahead_behind\))](bright-cyan) '


[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
format = '[➜ $state](bright-cyan)'
disabled = false


[python]
format = 'via [󰌠 $version(\($virtualenv)\)](bright-yellow)'


[java]
format = 'via [ $version](bright-red)'


[lua]
format = 'via [⏾ $version](blue)'


[c]
format = 'via [ $version](bright-blue)'


[nodejs]
format = 'via [ $version](bright-green)'


[character]
success_symbol = ''
error_symbol = ''
