
add_newline = true

format = """
[╭╴](238)$shell\
$username\
$directory\
$git_branch\
$git_status\
$fill\
$java\
$python\
$cmd_duration $time\ 
$line_break\
[╰─](238)$character"""

[fill]
symbol = " "

[shell]
bash_indicator = ''
powershell_indicator = ''
style = 'white bold'
disabled = false


[username]
style_user = 'purple bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

[directory]
use_os_path_sep = false
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "red"
read_only = " "
style = "bold green"
format = "at [$path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[](238)"
error_symbol = "[](238)"

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style)"
truncation_length = 4
truncation_symbol = "…"
style = "bold cyan"

[git_status]
format = '[\($all_status$ahead_behind\)]($style)'
style = "cyan"

up_to_date = " "
ahead = " ${count}"
diverged = " ${ahead_count} ${behind_count}"
behind = " ${count}"

conflicted = " " 
stashed = " "
modified = " "
untracked = " "
staged = " "
renamed = "襁 "
deleted = " "

[python]
symbol = " "
style = "blue"
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\) )]($style)'

[java]
symbol = ""
style = "bold red"
format = "[${symbol} (${version} )]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[time]
disabled = false
style = "white"
format = "[$time]($style)"
