return {
	-- 	"folke/noice.nvim",
	-- 	dependencies = {
	-- 		"MunifTanjim/nui.nvim",
	-- 		"rcarriga/nvim-notify",
	-- 	},
	-- 	config = function()
	-- 		require("noice").setup({
	-- 			views = {
	-- 				cmdline_popup = {
	-- 					position = {
	-- 						row = 3,
	-- 						col = "50%",
	-- 					},
	-- 				},
	-- 			},
	-- 			lsp = {
	-- 				override = {
	-- 					["vim.lsp.util.convert_input_to_markdown_lines"] = true,
	-- 					["vim.lsp.util.stylize_markdown"] = true,
	-- 					["cmp.entry.get_documentation"] = true,
	-- 				},
	-- 				progress = { enabled = false },
	-- 				documentation = { view = false },
	-- 			},
	-- 			cmdline = {
	-- 				format = {
	-- 					search_down = { kind = "search", pattern = "^/", icon = " ", lang = "regex" },
	-- 					search_up = { kind = "search", pattern = "^%?", icon = " ", lang = "regex" },
	-- 					filter = false,
	-- 					lua = false,
	-- 					input = {},
	-- 				},
	-- 			},
	-- 			routes = {
	-- 				{
	-- 					view = "notify",
	-- 					filter = { event = "msg_showmode" },
	-- 				},
	-- 			},
	-- 		})
	-- 		require("notify").setup({
	-- 			background_colour = "none",
	-- 			render = "compact",
	-- 			stages = "static",
	-- 			icons = {
	-- 				ERROR = "",
	-- 				WARN = "",
	-- 				INFO = "",
	-- 				DEBUG = "",
	-- 				TRACE = "",
	-- 			},
	-- 		})
	-- 	end,
}
